backend:
  name: github
  repo: adampugh/bluhorn-digital

media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: thumbnail, label: Featured Image, widget: image }
      - { name: body, label: Body, widget: markdown }
      - { name: sectionOne, label: SectionOne, widget: markdown }
      - { name: sectionTwo, label: SectionTwo, widget: markdown }
      # - { name: image, label: Image, widget: image, required: false }
